apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-k6
  template:
    metadata:
      labels:
        app: crm-k6
    spec:
      containers:
        - name: crm-k6
          image: grafana/k6
          command: ["k6", "run", "-o", "experimental-prometheus-rw", "/scripts/stress.js"]
          volumeMounts:
            - mountPath: /scripts
              name: k6-scripts
          env:
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: http://crm-prometheus:9090/api/v1/write
            - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts