apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
data:
  stress.js: |
    import http from 'k6/http';
    
    export const options = {
      vus: 1,
      duration: '30s'
    };
    
    export default function () {
      http.get('http://crm-app/api/v1/users');
    }