apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-dashboards-config
data:
  datasources.yml: |
    apiVersion: 1
    providers:
    - name: "k6 Stress Test"
      orgId: 1
      folder: ""
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /dashboard/k6.json
        foldersFromFilesStructure: true
    - name: "Log"
      orgId: 1
      folder: ""
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /dashboard/log.json
        foldersFromFilesStructure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources-config
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://crm-loki:3100
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://crm-prometheus:9090
