apiVersion: v1
kind: Service
metadata:
  name: crm-prometheus
spec:
  selector:
    app: crm-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: crm-loki
spec:
  selector:
    app: crm-loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: crm-grafana
spec:
  selector:
    app: crm-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
