apiVersion: v1
kind: Service
metadata:
  name: crm-mysql
spec:
  selector:
    app: crm-mysql
  ports:
    - protocol: TCP
      port: 13306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: crm-adminer
spec:
    selector:
        app: crm-adminer
    ports:
      - protocol: TCP
        port: 18080
        targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crm-redis
spec:
  selector:
    app: crm-redis
  ports:
    - protocol: TCP
      port: 16379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: crm-redis-insight
spec:
    selector:
        app: crm-redis-insight
    ports:
      - protocol: TCP
        port: 18081
        targetPort: 5540