apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      filesystem:
        directory: /loki/chunks
    limits_config:
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
      allow_structured_metadata: false
    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
    
