apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-loki
  template:
    metadata:
      labels:
        app: crm-loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yml
              subPath: loki-config.yml
          args:
            - "-config.file=/etc/loki/loki-config.yml"
      volumes:
        - name: loki-config
          configMap:
            name: loki-config