apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-prometheus
  template:
    metadata:
      labels:
        app: crm-prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          command: [
            "prometheus",
            "--web.enable-remote-write-receiver",
            "--enable-feature=native-histograms",
            "--config.file=/etc/prometheus/prometheus.yml"
          ]
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config