apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-adminer
  namespace: crm-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-adminer
  template:
    metadata:
      labels:
        app: crm-adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: "crm-mysql"
            - name: ADMINER_DESIGN
              value: "nette"
            - name: ADMINER_PLUGINS
              value: "tables-filter tinymce"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
