apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
        - name: crm-app
          image: crm-app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: crm-config
          ports:
            - containerPort: 8080