#!/bin/sh
# 스크립트 실패 시 즉시 종료
set -e

ORIGINAL_DIR=$(pwd)

echo "🚀 Building the application image..."

# Minikube 실행 상태 확인
if ! minikube status -p minikube &>/dev/null; then
  echo "❌ Minikube is not running. Please start minikube first."
  exit 1
fi

eval $(minikube -p minikube docker-env)

cd ../backend

docker build -t crm-app:latest .

cd "$ORIGINAL_DIR"

echo "✅ Application image built successfully."


