#!/bin/sh

set -e

echo "🚀 Starting Kubernetes deployment..."

ORIGINAL_DIR=$(pwd)
echo "📍Executing the script in the directory: $ORIGINAL_DIR"

echo "📂 Changing directory to application manifests..."
cd ../k8s/application

echo "🗑 Deleting existing application resources..."
kubectl delete -f . || echo "⚠️  Warning: Some resources might not exist."

echo "📦 Applying new application manifests..."
kubectl apply -f .

echo "✅ Application resources updated successfully."

echo "🔙 Returning to the original script directory: $ORIGINAL_DIR"
cd "$ORIGINAL_DIR"

echo "🎉 Kubernetes deployment completed!"