#!/bin/sh

ORIGINAL_DIR=$(pwd)

echo "🚀 Building the application image..."

eval $(minikube -p minikube docker-env)

cd ../

docker build -t crm-app:latest .

cd "$ORIGINAL_DIR"

echo "✅ Application image built successfully."


