apiVersion: v1
kind: Secret
metadata:
  name: crm-backend-secret
  namespace: crm-local
type: Opaque
stringData:
  SPRING_R2DBC_USERNAME: crm-local
  SPRING_R2DBC_PASSWORD: crm-local
  SPRING_R2DBC_ROUTING_USERNAME: crm-local
  SPRING_R2DBC_ROUTING_PASSWORD: crm-local
  SPRING_DATA_REDIS_CLUSTER_PASSWORD: password
  SPRING_AWS_CREDENTIALS_ACCESS_KEY: test
  SPRING_AWS_CREDENTIALS_SECRET_KEY: test
