name: Validate Test

on:
    pull_request:
        branches: [ "main", "dev" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    validate-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: 'temurin'

            -   name: Install docker-compose
                run: |
                    apt-get update && apt-get install -y docker-compose

            -   name: Prepare Test Environment
                run: |
                    cd ./scripts
                    ./local-develop-env-reset
                    sleep 10

            -   name: Validate Tests
                run: |
                    cd ./backend
                    ./gradlew test